"""Regression tests against the frozen baseline reference.

Oracle: ``tests/fixtures/test_vectors.json``, generated by running
``tests/baseline_reference.py`` (verbatim port of the original Colab
notebook cell 0) plus verbatim notebook metric formulas.  See
``docs/BASELINE_IMPLEMENTATION_AUDIT.md`` §10.

Any failure here means the refactored package no longer reproduces the
baseline — do not update the fixtures to make it pass; investigate first.
"""

from __future__ import annotations

import json
import math
from pathlib import Path

import numpy as np
import pytest

from aghc_s128 import (
    decrypt_bytes,
    encrypt_bytes,
    generate_valid_key,
)
from aghc_s128 import metrics as m

FIXTURES = Path(__file__).parent / "fixtures" / "test_vectors.json"


@pytest.fixture(scope="module")
def vectors():
    return json.loads(FIXTURES.read_text())


# ---------------------------------------------------------------------------
# Cipher vectors: byte-identical ciphertexts, keys, trials, round trips
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("index", range(13), ids=lambda i: f"vec{i}")
def test_ciphertext_matches_baseline(vectors, index):
    vector = vectors["cipher_vectors"][index]
    plaintext = np.frombuffer(bytes.fromhex(vector["plaintext_hex"]), dtype=np.uint8)
    result = encrypt_bytes(plaintext, vector["n_input"], vector["password"])
    assert result.ciphertext_sha3_256 == vector["ciphertext_sha3_256"], (
        f"ciphertext diverged for {vector['password']} n={vector['n_input']} "
        f"size={vector['plaintext_size']}"
    )


@pytest.mark.parametrize("index", range(13), ids=lambda i: f"vec{i}")
def test_key_matrix_matches_baseline(vectors, index):
    vector = vectors["cipher_vectors"][index]
    material = generate_valid_key(vector["n_input"], vector["password"])
    import hashlib

    key_digest = hashlib.sha3_256(
        material.matrix.astype(np.uint8).tobytes()
    ).hexdigest()
    inverse_digest = hashlib.sha3_256(
        material.inverse.astype(np.uint8).tobytes()
    ).hexdigest()
    assert key_digest == vector["key_matrix_sha3_256"]
    assert inverse_digest == vector["key_inverse_sha3_256"]
    assert material.trial_index == vector["trial_index"]


@pytest.mark.parametrize("index", range(13), ids=lambda i: f"vec{i}")
def test_round_trip_matches_baseline(vectors, index):
    vector = vectors["cipher_vectors"][index]
    plaintext = np.frombuffer(bytes.fromhex(vector["plaintext_hex"]), dtype=np.uint8)
    encrypted = encrypt_bytes(plaintext, vector["n_input"], vector["password"])
    decrypted = decrypt_bytes(
        encrypted.ciphertext, vector["n_input"], vector["password"],
        trial_index=vector["trial_index"],
    )
    assert decrypted.plaintext_sha3_256 == vector["plaintext_sha3_256"]
    np.testing.assert_array_equal(decrypted.plaintext, plaintext)


def test_nonzero_trial_vector_present(vectors):
    """At least one vector must exercise trial_index > 0 (retry path)."""
    nonzero = [v for v in vectors["cipher_vectors"] if v["trial_index"] > 0]
    assert nonzero, "expected at least one vector with trial_index > 0"
    assert any(v["trial_index"] == 5 for v in nonzero)


def test_ciphertext_hex_matches_baseline(vectors):
    for vector in vectors["cipher_vectors"]:
        if vector.get("ciphertext_hex"):
            plaintext = np.frombuffer(
                bytes.fromhex(vector["plaintext_hex"]), dtype=np.uint8
            )
            result = encrypt_bytes(plaintext, vector["n_input"], vector["password"])
            assert result.ciphertext.tobytes().hex() == vector["ciphertext_hex"]


# ---------------------------------------------------------------------------
# Metric vectors: notebook formulas vs library implementations
# ---------------------------------------------------------------------------


METRIC_KEYS = [
    ("entropy_a", lambda a, b: m.shannon_entropy(a)),
    ("entropy_b", lambda a, b: m.shannon_entropy(b)),
    ("npcr", lambda a, b: m.npcr(a, b)),
    ("uaci", lambda a, b: m.uaci(a, b)),
    ("bit_difference", lambda a, b: m.bit_difference_ratio(a, b)),
    ("chi_square", lambda a, b: m.chi_square_uniformity(b)[0]),
    ("chi_square_p", lambda a, b: m.chi_square_uniformity(b)[1]),
]


@pytest.mark.parametrize("metric_key,fn", METRIC_KEYS)
@pytest.mark.parametrize("case", ["mixed", "shift_only"])
def test_metrics_match_notebook(vectors, metric_key, fn, case):
    vector = vectors["metric_vectors"][case]
    a = np.frombuffer(bytes.fromhex(vector["a_hex"]), dtype=np.uint8)
    b = np.frombuffer(bytes.fromhex(vector["b_hex"]), dtype=np.uint8)
    expected = vector[metric_key]
    actual = fn(a, b)
    if isinstance(expected, float) and math.isnan(expected):
        assert math.isnan(float(actual))
    else:
        assert actual == pytest.approx(expected, rel=1e-12, abs=1e-12), (
            f"{case}/{metric_key}: library={actual} notebook={expected}"
        )


def test_correlation_matches_notebook(vectors):
    for case in ("mixed", "shift_only"):
        vector = vectors["metric_vectors"][case]
        a = np.frombuffer(bytes.fromhex(vector["a_hex"]), dtype=np.uint8)
        b = np.frombuffer(bytes.fromhex(vector["b_hex"]), dtype=np.uint8)
        assert m.adjacent_byte_correlation(a) == pytest.approx(
            vector["correlation_a"], rel=1e-12
        )
        assert m.adjacent_byte_correlation(b) == pytest.approx(
            vector["correlation_b"], rel=1e-12
        )


def test_monobit_matches_notebook_except_documented_underflow(vectors):
    """Monobit agrees with the notebook unless the notebook's unsigned
    subtraction underflowed (zeros > ones) — a documented baseline defect
    (docs/KNOWN_ISSUES.md).  Where it underflowed, the library must instead
    return the mathematically exact value of the same formula."""
    from scipy.stats import norm

    for case in ("mixed", "shift_only"):
        vector = vectors["metric_vectors"][case]
        b = np.frombuffer(bytes.fromhex(vector["b_hex"]), dtype=np.uint8)
        assert m.monobit_frequency_test(b) == pytest.approx(
            vector["monobit_b"], rel=1e-12
        )

    underflow = vectors["metric_vectors"]["low_entropy"]
    b = np.frombuffer(bytes.fromhex(underflow["b_hex"]), dtype=np.uint8)
    bits = np.unpackbits(b)
    ones, zeros = int(bits.sum()), bits.size - int(bits.sum())
    exact = 2 * (1 - norm.cdf(abs(ones - zeros) / np.sqrt(bits.size)))
    assert zeros > ones  # precondition for the notebook's underflow
    assert underflow["monobit_b"] == 0.0  # notebook's wrapped-around result
    assert m.monobit_frequency_test(b) == pytest.approx(float(exact))
    assert m.monobit_frequency_test(b) != pytest.approx(underflow["monobit_b"])


def test_truncated_notebook_behavior_reproducible(vectors):
    """allow_truncate=True reproduces the notebook's min-length numbers."""
    vector = vectors["metric_vectors"]["truncation_case"]
    a = np.frombuffer(bytes.fromhex(vector["a_hex"]), dtype=np.uint8)
    b = np.frombuffer(bytes.fromhex(vector["b_hex"]), dtype=np.uint8)
    assert a.size != b.size  # precondition: mismatched inputs
    assert m.npcr(a, b, allow_truncate=True) == pytest.approx(vector["npcr_truncated"])
    assert m.uaci(a, b, allow_truncate=True) == pytest.approx(vector["uaci_truncated"])
    assert m.bit_difference_ratio(a, b, allow_truncate=True) == pytest.approx(
        vector["bit_difference_truncated"]
    )
    with pytest.raises(ValueError):
        m.npcr(a, b)


# ---------------------------------------------------------------------------
# Direct structural equivalence with the baseline reference module
# ---------------------------------------------------------------------------


def test_perturbation_stream_identical_to_global_random_baseline():
    """The isolated random.Random instance must emit the baseline's stream."""
    import sys

    sys.path.insert(0, str(Path(__file__).parent))
    import baseline_reference as baseline

    from aghc_s128 import adaptive_graph_perturbation

    for size, seed in ((4, 1234), (8, 0xDEADBEEF), (16, 987654321)):
        np.testing.assert_array_equal(
            adaptive_graph_perturbation(size, seed),
            baseline.ai_graph_perturbation(size, seed),
        )


def test_logistic_map_identical_to_baseline():
    import sys

    sys.path.insert(0, str(Path(__file__).parent))
    import baseline_reference as baseline

    from aghc_s128 import logistic_map

    for seed in (0.54321, 0.12345, 0.999999):
        np.testing.assert_array_equal(
            logistic_map(seed, 100), baseline.logistic_map(seed, 100)
        )
